name: Playwright Tests - DEV
on:
  push:
  # It will triggered when there is a push on the following branches:
    branches: [ main, master ]
  # It will triggered when there is a pull request applied on the following branches:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      tags:
        type: choice
        description: 'Select a tag'
        options:
        - '@login'
        - '@smoke'
        
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --grep ${{ github.event.inputs.tag }}
      env:
        TESTUSER_USERNAME: ${{ secrets.TESTUSER_USERNAME }}
        TESTUSER_PASSWORD: ${{ secrets.TESTUSER_PASSWORD }}
        DEV_BASE_URL: ${{ secrets.DEV_BASE_URL }}
        DEV_TOKEN_URL: ${{ secrets.DEV_TOKEN_URL }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
